//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bravo.Automation.Creation {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    public sealed partial class Locators : global::System.Configuration.ApplicationSettingsBase {
        
        private static Locators defaultInstance = ((Locators)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Locators())));
        
        public static Locators Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("username")]
        public string Login_name_txt_username {
            get {
                return ((string)(this["Login_name_txt_username"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("password")]
        public string Login_name_txt_password {
            get {
                return ((string)(this["Login_name_txt_password"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//button")]
        public string Login_xpath_btn_login {
            get {
                return ((string)(this["Login_xpath_btn_login"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BtnAdd")]
        public string Users_id_btn_addnew {
            get {
                return ((string)(this["Users_id_btn_addnew"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("userName")]
        public string Users_name_txt_username {
            get {
                return ((string)(this["Users_name_txt_username"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("email")]
        public string Users_name_txt_email {
            get {
                return ((string)(this["Users_name_txt_email"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("password")]
        public string Users_name_txt_password {
            get {
                return ((string)(this["Users_name_txt_password"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("passwordConfirm")]
        public string Users_name_txt_repassword {
            get {
                return ((string)(this["Users_name_txt_repassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fullName")]
        public string Users_name_txt_fullname {
            get {
                return ((string)(this["Users_name_txt_fullname"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("roleID")]
        public string Users_name_ddl_role {
            get {
                return ((string)(this["Users_name_ddl_role"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("phone")]
        public string Users_name_txt_phone {
            get {
                return ((string)(this["Users_name_txt_phone"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//button[contains(@class,\'btn\')][contains(.,\'إضافة\')]")]
        public string Users_xpath_btn_save {
            get {
                return ((string)(this["Users_xpath_btn_save"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div.ui-notification-message.ng-binding")]
        public string Users_csslocator_div_notification {
            get {
                return ((string)(this["Users_csslocator_div_notification"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BtnAdd")]
        public string UserGroups_id_btn_addnew {
            get {
                return ((string)(this["UserGroups_id_btn_addnew"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("name")]
        public string UserGroups_name_txt_name {
            get {
                return ((string)(this["UserGroups_name_txt_name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//button[contains(@class,\'btn\')][contains(.,\'إضافه\')]")]
        public string UserGroups_xpath_btn_save {
            get {
                return ((string)(this["UserGroups_xpath_btn_save"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("txtSearch")]
        public string UserGroups_id_txt_search {
            get {
                return ((string)(this["UserGroups_id_txt_search"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//button[contains(@id,\'BtnDetails\')]")]
        public string UserGroups_xpath_icon_details {
            get {
                return ((string)(this["UserGroups_xpath_icon_details"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//button[contains(@id,\'BtnAdd\')][contains(.,\'إضافة مستخدمين\')]")]
        public string UserGroups_xpath_btn_addusers {
            get {
                return ((string)(this["UserGroups_xpath_btn_addusers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//tags-input/div/div")]
        public string UserGroups_xpath_txt_addsup {
            get {
                return ((string)(this["UserGroups_xpath_txt_addsup"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[2]/tags-input/div/div")]
        public string UserGroups_xpath_txt_addinsp {
            get {
                return ((string)(this["UserGroups_xpath_txt_addinsp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div.ui-notification-message.ng-binding")]
        public string UserGroups_csslocator_div_notification {
            get {
                return ((string)(this["UserGroups_csslocator_div_notification"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//ng-include/div/span")]
        public string UserGroups_xpath_option_user {
            get {
                return ((string)(this["UserGroups_xpath_option_user"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BtnUpdate")]
        public string UserGroups_id_btn_saveusers {
            get {
                return ((string)(this["UserGroups_id_btn_saveusers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("h2.ng-binding.ng-isolate-scope")]
        public string UserGroups_csslocator_header_title {
            get {
                return ((string)(this["UserGroups_csslocator_header_title"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@type=\'text\']")]
        public string UserGroups_xpath_txt_addsuptype {
            get {
                return ((string)(this["UserGroups_xpath_txt_addsuptype"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//input[@type=\'text\'])[2]")]
        public string UserGroups_xpath_txt_addinsptype {
            get {
                return ((string)(this["UserGroups_xpath_txt_addinsptype"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//button[contains(@id,\'BtnAdd\')][contains(.,\'نوع منشأة\')]")]
        public string EntityTypes_xpath_btn_addnew {
            get {
                return ((string)(this["EntityTypes_xpath_btn_addnew"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[contains(@name,\'typeName\')]")]
        public string EntityTypes_xpath_txt_name {
            get {
                return ((string)(this["EntityTypes_xpath_txt_name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[contains(@name,\'displayName\')]")]
        public string EntityTypes_xpath_txt_displayname {
            get {
                return ((string)(this["EntityTypes_xpath_txt_displayname"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//button[contains(@class,\'btn\')][contains(.,\'إضافة\')]")]
        public string EntityTypes_xpath_btn_save {
            get {
                return ((string)(this["EntityTypes_xpath_btn_save"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[contains(@placeholder,\'بحث\') or contains(@placeholder,\'Search\')]")]
        public string EntityTypes_xpath_txt_search {
            get {
                return ((string)(this["EntityTypes_xpath_txt_search"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//button[contains(@class,\'btnDetails\')]")]
        public string EntityTypes_xpath_icon_details {
            get {
                return ((string)(this["EntityTypes_xpath_icon_details"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div.ui-notification-message.ng-binding")]
        public string EntityTypes_csslocator_div_notification {
            get {
                return ((string)(this["EntityTypes_csslocator_div_notification"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//a[contains(@displayname,\'حقل نصي\') or contains(@displayname,\'TextBox\')]")]
        public string EntityTypes_xpath_a_textboxfield {
            get {
                return ((string)(this["EntityTypes_xpath_a_textboxfield"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//button[contains(.,\'Save\') or contains(.,\'حفظ\') and contains(@type,\'submit\')]")]
        public string EntityTypes_xpath_btn_savefields {
            get {
                return ((string)(this["EntityTypes_xpath_btn_savefields"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[contains(@class,\'noData\')]")]
        public string EntityTypes_xpath_div_griddrop {
            get {
                return ((string)(this["EntityTypes_xpath_div_griddrop"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//button[contains(@id,\'BtnAdd\')]")]
        public string EntityGroups_xpath_btn_addnew {
            get {
                return ((string)(this["EntityGroups_xpath_btn_addnew"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[contains(@name,\'name\')]")]
        public string EntityGroups_xpath_txt_name {
            get {
                return ((string)(this["EntityGroups_xpath_txt_name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//select[contains(@name,\'entityTypeId\')]")]
        public string EntityGroups_xpath_ddl_entitytype {
            get {
                return ((string)(this["EntityGroups_xpath_ddl_entitytype"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//button[contains(@class,\'btn\') and contains(.,\'Add\') or contains(.,\'إضافة\')]")]
        public string EntityGroups_xpath_btn_save {
            get {
                return ((string)(this["EntityGroups_xpath_btn_save"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[contains(@placeholder,\'بحث\') or contains(@placeholder,\'Search\')]")]
        public string EntityGroups_xpath_txt_search {
            get {
                return ((string)(this["EntityGroups_xpath_txt_search"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("i.fa.fa-file-text-o")]
        public string EntityGroups_csslocator_icon_details {
            get {
                return ((string)(this["EntityGroups_csslocator_icon_details"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//button[contains(@id,\'BtnAdd\') and contains(.,\'New Entity\') or contains(.,\'منشأة" +
            " جديدة\')]")]
        public string EntityGroups_xpath_btn_addnewentity {
            get {
                return ((string)(this["EntityGroups_xpath_btn_addnewentity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//button[contains(.,\'Create New Form\') or contains(.,\'نموذج جديد\')]")]
        public string FormBuilder_xpath_btn_addnew {
            get {
                return ((string)(this["FormBuilder_xpath_btn_addnew"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("formName")]
        public string FormBuilder_id_btn_formname {
            get {
                return ((string)(this["FormBuilder_id_btn_formname"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("formDisplayName")]
        public string FormBuilder_id_btn_formdisplayname {
            get {
                return ((string)(this["FormBuilder_id_btn_formdisplayname"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[5]/p-checkbox/div/div[2]")]
        public string FormBuilder_xpath_chk_scheduled {
            get {
                return ((string)(this["FormBuilder_xpath_chk_scheduled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//button[contains(@type,\'submit\') and contains(.,\'إضافة\') or contains(.,\'Add\')]")]
        public string FormBuilder_xpath_btn_addform {
            get {
                return ((string)(this["FormBuilder_xpath_btn_addform"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div.ui-notification-message.ng-binding")]
        public string FormBuilder_csslocator_div_notification {
            get {
                return ((string)(this["FormBuilder_csslocator_div_notification"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("float-input")]
        public string FormBuilder_id_txt_search {
            get {
                return ((string)(this["FormBuilder_id_txt_search"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div.col-lg-12.card-header > a")]
        public string FormBuilder_csslocator_div_formdispname {
            get {
                return ((string)(this["FormBuilder_csslocator_div_formdispname"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[@id=\'formControls\']/div/div/i")]
        public string FormBuilder_xpath_a_textinputfield {
            get {
                return ((string)(this["FormBuilder_xpath_a_textinputfield"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("currentBuilderModel")]
        public string FormBuilder_id_div_griddrop {
            get {
                return ((string)(this["FormBuilder_id_div_griddrop"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//button[contains(.,\'Save\') or contains(.,\'حفظ\')]")]
        public string FormBuilder_xpath_btn_save {
            get {
                return ((string)(this["FormBuilder_xpath_btn_save"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("i.fa.fa-sitemap")]
        public string Workflow_csslocator_icon_workflowsteps {
            get {
                return ((string)(this["Workflow_csslocator_icon_workflowsteps"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[contains(.,\'إجراء جديد\') and contains(@class,\'btn\')]")]
        public string Workflow_xpath_btn_startnewaction {
            get {
                return ((string)(this["Workflow_xpath_btn_startnewaction"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//button[contains(.,\'Save\') or contains(.,\'حفظ\')]")]
        public string Workflow_xpath_btn_save {
            get {
                return ((string)(this["Workflow_xpath_btn_save"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("i.icon-inspector")]
        public string Workflow_csslocator_icon_startinspector {
            get {
                return ((string)(this["Workflow_csslocator_icon_startinspector"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("name")]
        public string Workflow_name_txt_actionname {
            get {
                return ((string)(this["Workflow_name_txt_actionname"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("actionTypeSelect")]
        public string Workflow_name_txt_actiontype {
            get {
                return ((string)(this["Workflow_name_txt_actiontype"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("triggerTypeSelect")]
        public string Workflow_name_txt_actiontrigger {
            get {
                return ((string)(this["Workflow_name_txt_actiontrigger"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nextStepSelect")]
        public string Workflow_name_txt_actionnextstep {
            get {
                return ((string)(this["Workflow_name_txt_actionnextstep"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BtnUpdate")]
        public string Workflow_id_btn_addaction {
            get {
                return ((string)(this["Workflow_id_btn_addaction"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("name")]
        public string EntityGroups_name_txt_entityname {
            get {
                return ((string)(this["EntityGroups_name_txt_entityname"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("weight")]
        public string EntityGroups_name_txt_entityweight {
            get {
                return ((string)(this["EntityGroups_name_txt_entityweight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("longitude")]
        public string EntityGroups_name_txt_entitylong {
            get {
                return ((string)(this["EntityGroups_name_txt_entitylong"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("latitude")]
        public string EntityGroups_name_txt_entitylat {
            get {
                return ((string)(this["EntityGroups_name_txt_entitylat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@type=\'text\']")]
        public string EntityGroups_xpath_txt_entitytypefield {
            get {
                return ((string)(this["EntityGroups_xpath_txt_entitytypefield"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//button[contains(.,\'إضافة\') or contains(.,\'Add\')]")]
        public string EntityGroups_xpath_btn_saveentity {
            get {
                return ((string)(this["EntityGroups_xpath_btn_saveentity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("li.add-step.ng-scope")]
        public string Workflow_csslocator_icon_addstep {
            get {
                return ((string)(this["Workflow_csslocator_icon_addstep"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[@id=\'tab\']/ng-form[2]/workflow-actors-component/div/div/div/a[3]/div/center" +
            "/i")]
        public string Workflow_xpath_icon_stepsupervisor {
            get {
                return ((string)(this["Workflow_xpath_icon_stepsupervisor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//form/ul/li[2]")]
        public string Workflow_xpath_icon_stepone {
            get {
                return ((string)(this["Workflow_xpath_icon_stepone"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BtnAdd")]
        public string Linking_id_btn_newlink {
            get {
                return ((string)(this["Linking_id_btn_newlink"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("entityGroupsSelect")]
        public string Linking_id_select_entitygroup {
            get {
                return ((string)(this["Linking_id_select_entitygroup"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("formsSelect")]
        public string Linking_id_select_form {
            get {
                return ((string)(this["Linking_id_select_form"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("userGroupsSelect")]
        public string Linking_id_select_usergroup {
            get {
                return ((string)(this["Linking_id_select_usergroup"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//button[contains(@id,\'BtnUpdate\') and contains(.,\'Add\') or contains(.,\'إضافة\')]")]
        public string Linking_xpath_btn_savelink {
            get {
                return ((string)(this["Linking_xpath_btn_savelink"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div.ui-notification-message.ng-binding")]
        public string Linking_csslocator_div_notification {
            get {
                return ((string)(this["Linking_csslocator_div_notification"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("span.ui-inputswitch-slider")]
        public string FormBuilder_csslocator_icon_switchactivate {
            get {
                return ((string)(this["FormBuilder_csslocator_icon_switchactivate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[2]/a[2]/i")]
        public string EntityTypes_xpath_icon_edittextboxfield {
            get {
                return ((string)(this["EntityTypes_xpath_icon_edittextboxfield"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[2]/input")]
        public string EntityTypes_xpath_txt_textboxfieldnamedb {
            get {
                return ((string)(this["EntityTypes_xpath_txt_textboxfieldnamedb"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[3]/button")]
        public string EntityTypes_xpath_txt_savetextboxdetailsfield {
            get {
                return ((string)(this["EntityTypes_xpath_txt_savetextboxdetailsfield"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[contains(@draggable,\'true\') and contains(@class,\'single-entity\')]")]
        public string Taskdistribution_xpath_div_singleentity {
            get {
                return ((string)(this["Taskdistribution_xpath_div_singleentity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[contains(@id,\'#\')]/div/ul")]
        public string Taskdistribution_xpath_div_droptoday {
            get {
                return ((string)(this["Taskdistribution_xpath_div_droptoday"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//button[contains(@id,\'reload-button\')]")]
        public string test_xpath_fake {
            get {
                return ((string)(this["test_xpath_fake"]));
            }
            set {
                this["test_xpath_fake"] = value;
            }
        }
    }
}
